spring:
  profiles:
    active: dev # ????dev??
  application:
    name: syncnote-document

# ???????profile???????
storage:
  minio:
    endpoint: ${MINIO_ENDPOINT:http://localhost:9000}
    accessKey: ${MINIO_ACCESS_KEY:minioadmin}
    secretKey: ${MINIO_SECRET_KEY:minioadmin}
    bucket: ${MINIO_BUCKET:syncnote-documents}